general:
  # Commands to run when the WM has started. This is useful for running a
  # script or launching another application.
  # Example: The below command launches Zebar.
  startup_commands:
    [
      'shell-exec zebar',
    ]

  # Commands to run just before the WM is shutdown.
  # Example: The below command kills Zebar.
  shutdown_commands:
    [
      'shell-exec taskkill /IM zebar.exe /F',
    ]

  # Commands to run after the WM config is reloaded.
  config_reload_commands: []

  # Whether to automatically focus windows underneath the cursor.
  focus_follows_cursor: false

  # Whether to switch back and forth between the previously focused
  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false

  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true

    # Trigger for cursor jump:
    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    trigger: 'monitor_focus'

gaps:
  # Gap between adjacent windows.
  inner_gap: '6px'

  # Gap between windows and the screen edge.
  outer_gap:
    top: '40px'
    right: '6px'
    bottom: '6px'
    left: '6px'

window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: '#0000cc'

    # Remove the title bar from the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    hide_title_bar:
      enabled: true

    # Change the corner style of the window's frame.
    # ** Exclusive to Windows 11 due to API limitations.
    corner_style:
      enabled: true
      # Allowed values: 'square', 'rounded', 'small_rounded'.
      style: 'small_rounded'

  # Visual effects to apply to non-focused windows.
  other_windows:
    border:
      enabled: true
      color: '#aaaaaa'
    hide_title_bar:
      enabled: true
    corner_style:
      enabled: true
      style: 'small_rounded'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: false

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:
  - commands: ['ignore']
    match:
      # Ignores any Zebar windows.
      - window_process: { equals: 'zebar' }

      # Ignores task manager processes.
      - window_process: { regex: 'Taskmgr|Registry|regedit|ScreenClippingHost' }
      # - window_process: { regex: 'ScreenClippingHost' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { equals: 'mstsc' }
        window_class: { regex: 'TscShellContainerClass' }

      # Ignores picture-in-picture windows for browsers.
      - window_title: { regex: '[Pp]icture.in.[Pp]icture' }
        window_class: { regex: 'Chrome_WidgetWin_1|MozillaDialogClass' }

      # Ignore rules for various 3rd-party apps.
      - window_process: { regex: 'PowerToys' }
        window_class: { regex: 'HwndWrapper\[PowerToys\.PowerAccent.*?\]' }

      - window_process: { equals: 'Lively' }
        window_class: { regex: 'HwndWrapper*' }

      - window_process: { regex: 'msedgewebview2' }
        window_class: { regex: '#32770' }
        window_title: { regex: 'Open' }

      - window_class: { regex: '[Ss]hell_[Dd]ialog' }

  - commands: ['set-floating']
    match:
      - window_process: { regex: 'OUTLOOK' }
        window_class: { regex: 'rctrl_renwnd32' }
        window_title: { regex: 'Appointment' }

      - window_process: { regex: 'ms-teams|ms-teams.exe' }
        window_class: { regex: 'TeamsWebView' }
        window_title: { regex: '[Nn]ew [Mm]eeting' }

      - window_process: { regex: 'mRemoteNG' }
        window_title: { includes: 'mRemoteNG' }

      - window_process: { regex: 'TrGUI|TrGUI\.exe' }
        window_class: { regex: 'Qt51510QWindowIcon' }

      - window_process: { regex: 'msedge' }
        window_class: { regex: 'Chrome_WidgetWin_1' }
        window_title: { regex: 'Bitwarden' }

      - window_process: { regex: 'Taskmgr|regedit' }
      - window_process: { regex: 'explorer|explorer\.exe' }
      - window_process: { regex: 'PSRClient' }
      - window_process: { regex: '1Password' }
      - window_process: { regex: 'MSPCManager' }
      - window_process: { regex: 'SnippingTool' }
      - window_process: { regex: 'notificationtoasts_' }
      - window_process: { regex: 'SystemInformer' }
      - window_process: { regex: 'winzip64' }
      - window_process: { regex: 'msiexec' }
      - window_process: { regex: 'CredentialUIBroker' }
      - window_process: { regex: 'LogiBolt|LogiTune|LogiOptionsUI' }
      - window_process: { regex: 'NohBoard' }
      - window_process: { regex: 'Paradox Launcher' }
      # - window_process: { regex: 'PowerToys' }
      - window_process: { regex: 'PowerToys\.ColorPickerUI|PowerToys\.ImageResizer' }
      - window_process: { regex: 'ProcessHacker' }
      - window_process: { regex: 'QuickLook' }
      - window_process: { regex: 'RepoZ' }
      - window_process: { regex: 'RoundedTB' }
      - window_process: { regex: 'tcconfig' }
      - window_process: { regex: 'TranslucentTB' }
      - window_process: { regex: 'ueli' }
      - window_process: { regex: 'Zoom' }

      - window_class: { regex: '#32770' }
      - window_class: { regex: 'NotifyIconOverflowWindow' }
      - window_class: { regex: 'CabinetWClass' }
      - window_class: { regex: 'Qt5QWindowIcon' }
      - window_class: { regex: 'TApplication' }
      - window_class: { regex: 'TWizardForm' }
      - window_class: { regex: '_WwB' }
      - window_class: { regex: 'MozillaTaskbarPreviewClass' }
      - window_class: { regex: 'SunAwtDialog' }
      - window_class: { regex: 'Chrome_RenderWidgetHostHWND' }
      - window_class: { regex: 'Shell_Dialog' }
      - window_class: { regex: 'TaskManagerWindow' }
      - window_class: { regex: 'OperationStatusWindow' }
      - window_class: { regex: 'MsiDialogCloseClass' }

      - window_title: { regex: 'Calculator' }
      - window_title: { regex: 'notificationtoasts_' }
      - window_title: { regex: '[Mm]icrosoft [Tt]eams [Nn]otifications' }
      - window_title: { regex: '[Cc]ontrol [Pp]anel' }
      - window_title: { regex: '[Ww]indow [Ss]py' }

  - commands: ['move --workspace 1']
    match:
      - window_process: { regex: 'ms-teams|slack' }
  - commands: ['move --workspace 2']
    match:
      - window_process: { regex: 'msedge|chrome|brave' }
  - commands: ['move --workspace 3']
    match:
      - window_process: { regex: 'Code' }
  - commands: ['move --workspace 4']
    match:
      - window_process: { regex: 'WindowsTerminal' }
  - commands: ['move --workspace 9']
    match:
      - window_process: { regex: 'Яндекс Музыка' }

binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: 'resize'
    keybindings:
      - commands: ['resize --width -2%']
        bindings: ['h', 'left']
      - commands: ['resize --width +2%']
        bindings: ['l', 'right']
      - commands: ['resize --height +2%']
        bindings: ['k', 'up']
      - commands: ['resize --height -2%']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name resize']
        bindings: ['escape', 'enter']

  - name: 'move'
    keybindings:
      # move focused window.
      - commands: ['move --direction left']
        bindings: ['h', 'left']
      - commands: ['move --direction right']
        bindings: ['l', 'right']
      - commands: ['move --direction up']
        bindings: ['k', 'up']
      - commands: ['move --direction down']
        bindings: ['j', 'down']
      # Press enter/escape to return to default keybindings.
      - commands: ['wm-disable-binding-mode --name move']
        bindings: ['escape', 'enter']

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:
  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+h', 'alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+l', 'alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+k', 'alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+j', 'alt+down']

  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+h', 'alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+l', 'alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+k', 'alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+j', 'alt+shift+down']

  # Resize focused window by a percentage or pixel amount.
  - commands: ['resize --width -2%']
    bindings: ['alt+oem_comma']
  - commands: ['resize --width +2%']
    bindings: ['alt+oem_period']
  - commands: ['resize --height +2%']
    bindings: ['alt+shift+oem_period']
  - commands: ['resize --height -2%']
    bindings: ['alt+shift+oem_comma']

  # As an alternative to the resize keybindings above, resize mode enables
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  # the name 'resize'.
  - commands: ['wm-enable-binding-mode --name resize']
    bindings: ['alt+r']

  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ['wm-enable-binding-mode --name pause']
    bindings: ['alt+shift+p']

  # Enables moving the focused window via arrow keys or HJKL.
  - commands: ['wm-enable-binding-mode --name move']
    bindings: ['alt+m']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+v']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+ctrl+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  - commands: ['toggle-tiling']
    bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['alt+f']

  # # Minimize focused window.
  # - commands: ['toggle-minimized']
  #   bindings: ['alt+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['alt+shift+q']

  # # Kill GlazeWM process safely.
  # - commands: ['wm-exit']
  #   bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

  # Launch windows terminal (alternatively `exec %ProgramFiles%/Git/git-bash.exe`
  # Git Bash.
  - commands: ['shell-exec wt']
    bindings: ['alt+enter']

  # Launch browser
  - commands: ['shell-exec msedge']
    bindings: ['alt+shift+enter']

  # Focus the next/previous workspace defined in `workspaces` config.
  # - commands: ['focus --next-workspace']
  #   bindings: ['alt+s']
  # - commands: ['focus --prev-workspace']
  #   bindings: ['alt+a']

  # Focus the workspace that last had focus.
  - commands: ['focus --recent-workspace']
    bindings: ['alt+oem_tilde']

  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['alt+1']
  - commands: ['focus --workspace 2']
    bindings: ['alt+2']
  - commands: ['focus --workspace 3']
    bindings: ['alt+3']
  - commands: ['focus --workspace 4']
    bindings: ['alt+4']
  - commands: ['focus --workspace 5']
    bindings: ['alt+5']
  - commands: ['focus --workspace 6']
    bindings: ['alt+6']
  - commands: ['focus --workspace 7']
    bindings: ['alt+7']
  - commands: ['focus --workspace 8']
    bindings: ['alt+8']
  - commands: ['focus --workspace 9']
    bindings: ['alt+9']

  # Move the focused window's parent workspace to a monitor in a given
  # direction.
  - commands: ['move-workspace --direction left']
    bindings: ['ctrl+alt+shift+h']
  - commands: ['move-workspace --direction right']
    bindings: ['ctrl+alt+shift+l']
  - commands: ['move-workspace --direction up']
    bindings: ['ctrl+alt+shift+k']
  - commands: ['move-workspace --direction down']
    bindings: ['ctrl+alt+shift+j']

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['alt+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['alt+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['alt+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['alt+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['alt+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['alt+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['alt+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['alt+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['alt+shift+9']
